version: '3'
services:
  redis:
    build: redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    restart: on-failure
  datastax:
    build: datastax
    depends_on:
      - redis
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    links:
      - redis
    volumes:
      - /tmp:/opt/datastax_app/logs
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - FILE_ACL=${FILE_ACL:-private}
      - S3_BUCKET=${S3_BUCKET:-dmc-srodriguez-20181130}
      - UPLOAD_URL_TTL=${UPLOAD_URL_TTL:-3600}
      - DOWNLOAD_URL_TTL=${DOWNLOAD_URL_TTL:-60}
      - API_PORT=${API_PORT:-8080}
      - WORKERS=${WORKERS:-1}
    restart: on-failure
  tests:
    build: tests
    depends_on:
      - datastax
      - redis
    links:
      - datastax
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - API_HOST=${API_HOST:-datastax}
      - API_PORT=${API_PORT:-8080}
    restart: on-failure
